---
language: python
services: docker

matrix:
  include:
    - os: linux
      dist: xenial

before_script:
  - cd ../
  - mv ansible-role-deploy-prometheus deploy-prometheus
  - cd deploy-prometheus

install:
  - pip install molecule docker

script:
  - molecule lint
