---
- name: Restart the Prometheus service
  service:
    name: prometheus
    state: restarted
  listen: restart_prometheus
  when: prom_syntax_check.rc == 0

- name: Reload systemd
  systemd:
    daemon_reload: yes
  listen: reload_systemd
  when: copy_systemd_service.changed
