---
- name: Restart the Prometheus service
  service:
    name: prometheus
    state: restarted
  listen: restart_prometheus

- name: Reload systemd
  systemd:
    daemon_reload: yes
  listen: systemd_reload
